name: Emotion Analysis

on:
  push:
    paths:
      - 'data/**'
  workflow_dispatch:

jobs:
  analyze:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install numpy pandas scikit-learn scipy joblib
        
    - name: Run analysis script
      run: |
        python scripts/analyze_emotion.py
        
    - name: Commit results
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add analysis_results.json
        git commit -m "Update emotion analysis results" || echo "No changes to commit"
        git push
