name: Emotion Analysis

on:
  push:
    paths:
      - 'data/**'
  workflow_dispatch:

jobs:
  analyze:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # 添加写入权限
    
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0  # 获取完整历史
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install numpy pandas scikit-learn scipy joblib
        
    - name: Run analysis script
      run: |
        python scripts/analyze_emotion.py
        
    - name: Commit results
      run: |
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        # 创建空的结果文件（如果不存在）
        touch analysis_results.json
        touch analysis_summary.json
        # 添加所有更改
        git add .
        # 尝试提交
        git commit -m "Update emotion analysis results" || echo "No changes to commit"
        # 推送更改
        git push origin ${GITHUB_REF#refs/heads/}
